export const ERROR = {
    USER_EXISTS: "User already exists",
    USER_DOESNT_EXISTS: "User doesn't exist",
    USER_NOT_FOUND: "User not found",
    COMPANY_EXISTS: "Company already exists",
    COMPANY_NOT_FOUND: "Company not found",
    INVALID_CREDENTIALS: "Invalid credentials",
    UNAUTHORIZED: "Unauthorized access",
    FORBIDDEN: "Forbidden access",
    CHAT_NOT_FOUND: "Chat not found",
    AI_FAILED: "AI response failed",
    INTERNAL_SERVER_ERROR: "Something Went Wrong!",
    VALIDATION_FAILURE: "Validation Failure",
    ROUTE_NOT_FOUND: "Route not found",
};
