export const LOG = {
    // AUTH
    AUTH_REGISTER_START: "AUTH_REGISTER_START",
    AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
    AUTH_REGISTER_FAILED: "AUTH_REGISTER_FAILED",

    AUTH_LOGIN_START: "AUTH_LOGIN_START",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",

    // AUTH MIDDLEWARE
    AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
    AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",

    // SYSTEM
    SERVER_START: "SERVER_STARTED",
    DATABASE_CONNECTED: "DATABASE_CONNECTED",
    DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
};
