export const LOG = {
    // AUTH
    AUTH_REGISTER_START: "AUTH_REGISTER_START",
    AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
    AUTH_REGISTER_FAILED: "AUTH_REGISTER_FAILED",

    AUTH_LOGIN_START: "AUTH_LOGIN_START",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",

    // AUTH MIDDLEWARE
    AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
    AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",

    // COMPANY 
    COMPANY_CREATE_START: "COMPANY_CREATE_START",
    COMPANY_CREATE_SUCCESS: "COMPANY_CREATE_SUCCESS",
    COMPANY_CREATE_FAILED: "COMPANY_CREATE_FAILED",
    COMPANY_UPDATE_START: "COMPANY_UPDATE_START",
    COMPANY_UPDATE_SUCCESS: "COMPANY_UPDATE_SUCCESS",
    COMPANY_FETCH_START: "COMPANY_FETCH_START",
    COMPANY_FETCH_SUCCESS: "COMPANY_FETCH_SUCCESS",
    COMPANY_DELETE_START: "COMPANY_DELETE_START",
    COMPANY_DELETE_SUCCESS: "COMPANY_DELETE_SUCCESS",

    // SYSTEM
    SERVER_START: "SERVER_STARTED",
    DATABASE_CONNECTED: "DATABASE_CONNECTED",
    DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
};
