export const LOG = {
    // AUTH
    AUTH_REGISTER_START: "AUTH_REGISTER_START",
    AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
    AUTH_REGISTER_FAILED: "AUTH_REGISTER_FAILED",

    AUTH_LOGIN_START: "AUTH_LOGIN_START",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",

    // AUTH MIDDLEWARE
    AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
    AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",

    // COMPANY 
    COMPANY_CREATE_START: "COMPANY_CREATE_START",
    COMPANY_CREATE_SUCCESS: "COMPANY_CREATE_SUCCESS",
    COMPANY_CREATE_FAILED: "COMPANY_CREATE_FAILED",
    COMPANY_UPDATE_START: "COMPANY_UPDATE_START",
    COMPANY_UPDATE_SUCCESS: "COMPANY_UPDATE_SUCCESS",
    COMPANY_FETCH_START: "COMPANY_FETCH_START",
    COMPANY_FETCH_SUCCESS: "COMPANY_FETCH_SUCCESS",
    COMPANY_DELETE_START: "COMPANY_DELETE_START",
    COMPANY_DELETE_SUCCESS: "COMPANY_DELETE_SUCCESS",

    // DEPARTMENT
    DEPARTMENT_CREATE_START: "DEPARTMENT_CREATE_START",
    DEPARTMENT_CREATE_SUCCESS: "DEPARTMENT_CREATE_SUCCESS",
    DEPARTMENT_CREATE_FAILED: "DEPARTMENT_CREATE_FAILED",
    DEPARTMENT_UPDATE_START: "DEPARTMENT_UPDATE_START",
    DEPARTMENT_UPDATE_SUCCESS: "DEPARTMENT_UPDATE_SUCCESS",
    DEPARTMENT_UPDATE_FAILED: "DEPARTMENT_UPDATE_FAILED",
    DEPARTMENT_FETCH_START: "DEPARTMENT_FETCH_START",
    DEPARTMENT_FETCH_SUCCESS: "DEPARTMENT_FETCH_SUCCESS",
    DEPARTMENT_FETCH_FAILED: "DEPARTMENT_FETCH_FAILED",
    DEPARTMENT_DELETE_START: "DEPARTMENT_DELETE_START",
    DEPARTMENT_DELETE_SUCCESS: "DEPARTMENT_DELETE_SUCCESS",
    DEPARTMENT_DELETE_FAILED: "DEPARTMENT_DELETE_FAILED",
    // STUDENT
    STUDENT_FETCH_START: "STUDENT_FETCH_START",
    STUDENT_FETCH_SUCCESS: "STUDENT_FETCH_SUCCESS",
    STUDENT_UPDATE_START: "STUDENT_UPDATE_START",
    STUDENT_UPDATE_SUCCESS: "STUDENT_UPDATE_SUCCESS",
    STUDENT_UPDATE_FAILED: "STUDENT_UPDATE_FAILED",

    // SYSTEM
    SERVER_START: "SERVER_STARTED",
    DATABASE_CONNECTED: "DATABASE_CONNECTED",
    DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
};
